# Site settings
title: Guillaume Voisin
html_title: Freelancer - Guillaume Voisin - Full Stack Web Developer
email: guillaume.voisin29@gmail.com
url: https://voising.github.io
description: "Guillaume Voisin portfolio. I make Minimum Viable Product (MVP) - E-commerce / E-shop - Corporate website - One page design."
skills: "Ruby on Rails Full Stack Engineer"
meta_author: Guillaume Voisin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e74c3c #18bc9c #80B3FF
  primary-rgb: "192, 57, 43" #"231,76,60" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Guillaume Voisin
  location: Location
  social: Around the Web
  credits: Infos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/voising
  - title: github
    url: http://github.com/voising
  - title: linkedin
    url: https://fr.linkedin.com/in/guillaume-voisin-b5190446
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url:
#  - title: bitbucket
#    url:

# Postal address (add as many lines as necessary)
address:
  - line: Europe

# Credits content
credits: '<a href="mailto:guillaume.voisin29@gmail.com?subject=[Freelance] More infos"><i class="fa fa-envelope-o"></i>guillaume.voisin29@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty

languages: ["en", "fr"]
exclude_from_localizations: ["javascript", "img", "js", "css"]
